#!/usr/bin/env bash
# Local runner — the deployment.md Appendix A stack, entirely in Docker.
# No local Java or Gradle: the jar is built by the repo's pinned Gradle wrapper
# inside a throwaway JDK container, packaged with the repo Dockerfile, and run
# via deploy/docker-compose.yml + deploy/docker-compose.local.yml — the same
# stack an engineer evaluating the project runs.
#
#   ./app.sh --start [--no-build]   build image in Docker + start the full stack
#   ./app.sh --stop                 stop the stack (Postgres data volume kept)
#   ./app.sh --status               show services + app health
#   ./app.sh --logs                 follow the app container's logs
#
# Secrets live in deploy/.env (git-ignored). If it is missing, --start scaffolds
# it: values are carried over from .env.local when present (JWT/encryption/OIDC),
# infra passwords are generated. The Gradle cache persists in ./.gradle-docker
# (git-ignored), so only the first build is cold.
# (--demo — bring up the shipped sample databases too — arrives with the
# sample-data slice; the loader it wraps does not exist yet.)

set -euo pipefail
cd "$(cd "$(dirname "$0")" && pwd)"

DEPLOY_ENV="deploy/.env"
LOCAL_ENV=".env.local"
COMPOSE=(docker compose -f deploy/docker-compose.yml -f deploy/docker-compose.local.yml)
IMAGE_TAG="datapipelines:local"
BUILDER_IMAGE="eclipse-temurin:21-jdk"
GRADLE_CACHE="$PWD/.gradle-docker"
HEALTH_URL="http://localhost:8080/health"

die() { echo "app.sh: $*" >&2; exit 1; }

# Read KEY=value from a dotenv file; empty when absent.
env_get() { # file key
  [[ -f $1 ]] || return 0
  grep -E "^$2=" "$1" | head -1 | cut -d= -f2-
}

scaffold_deploy_env() {
  [[ -f $DEPLOY_ENV ]] && return 0
  echo "==> $DEPLOY_ENV missing — scaffolding it (secrets carried from $LOCAL_ENV where present)"
  local jwt enc base gid gsec admin domains
  jwt=$(env_get "$LOCAL_ENV" DATAPIPELINES_JWT_SECRET)
  enc=$(env_get "$LOCAL_ENV" DATAPIPELINES_DB_ENCRYPTION_KEY)
  base=$(env_get "$LOCAL_ENV" DATAPIPELINES_AUTH_BASE_URL)
  gid=$(env_get "$LOCAL_ENV" GOOGLE_CLIENT_ID)
  gsec=$(env_get "$LOCAL_ENV" GOOGLE_CLIENT_SECRET)
  admin=$(env_get "$LOCAL_ENV" DATAPIPELINES_AUTH_BOOTSTRAP_ADMIN_EMAIL)
  domains=$(env_get "$LOCAL_ENV" DATAPIPELINES_AUTH_ALLOWLIST_DOMAINS)
  cat >"$DEPLOY_ENV" <<EOF
# Generated by app.sh $(date +%F) from .env.local + fresh infra passwords.
# Git-ignored. See deploy/.env.example for the field reference.
METADATA_DB_PASSWORD=$(openssl rand -base64 24)
REDIS_PASSWORD=$(openssl rand -base64 24)
JWT_SECRET=${jwt:-$(openssl rand -base64 32)}
ENCRYPTION_KEY=${enc:-$(openssl rand -base64 32)}
DATAPIPELINES_AUTH_BASE_URL=${base:-http://localhost:8080}
GOOGLE_CLIENT_ID=${gid:-your-google-client-id}
GOOGLE_CLIENT_SECRET=${gsec:-your-google-client-secret}
# This email becomes admin at its FIRST login (auth.md §4.4); empty = no admin
DATAPIPELINES_AUTH_BOOTSTRAP_ADMIN_EMAIL=${admin:-}
DATAPIPELINES_AUTH_ALLOWLIST_DOMAINS=${domains:-}
EOF
  echo "==> wrote $DEPLOY_ENV — review it; Google creds must be real for login to work"
}

build() {
  echo "==> building jar with the pinned Gradle wrapper in $BUILDER_IMAGE (cache: .gradle-docker/)"
  mkdir -p "$GRADLE_CACHE"
  docker run --rm \
    -v "$PWD":/ws -w /ws \
    -u "$(id -u)":"$(id -g)" \
    -e HOME=/tmp -e GRADLE_USER_HOME=/ws/.gradle-docker \
    "$BUILDER_IMAGE" ./gradlew :modules:app:bootJar
  echo "==> building image $IMAGE_TAG"
  docker build -t "$IMAGE_TAG" .
}

start() {
  local do_build=1
  [[ ${1:-} == --no-build ]] && do_build=0
  scaffold_deploy_env
  if ((do_build)); then
    build
  else
    docker image inspect "$IMAGE_TAG" >/dev/null 2>&1 \
      || die "image $IMAGE_TAG not found — run --start without --no-build first"
  fi
  echo "==> starting the stack (app healthcheck probes /ready; first boot runs migrations)"
  if ! "${COMPOSE[@]}" up -d --wait; then
    echo "---- app container, last 40 log lines ----"
    "${COMPOSE[@]}" logs --tail 40 datapipelines || true
    die "stack did not become healthy — full logs: ./app.sh --logs"
  fi
  curl -sf "$HEALTH_URL" >/dev/null 2>&1 \
    || die "stack is up but $HEALTH_URL is not answering"
  echo "==> UP — http://localhost:8080"
}

stop() {
  echo "==> stopping the stack (data volume kept; '${COMPOSE[*]} down -v' resets it)"
  "${COMPOSE[@]}" stop
}

status() {
  "${COMPOSE[@]}" ps
  if curl -sf "$HEALTH_URL" >/dev/null 2>&1; then
    echo "health: UP ($HEALTH_URL)"
  else
    echo "health: NOT RESPONDING ($HEALTH_URL)"
  fi
}

case ${1:-} in
  --start)
    shift
    start "$@"
    ;;
  --stop) stop ;;
  --status) status ;;
  --logs) exec "${COMPOSE[@]}" logs -f datapipelines ;;
  *)
    grep '^#   ' "$0" | sed 's/^#   //'
    exit 2
    ;;
esac
