-- =============================================================================
-- V39 — parameter sets (#194, parameter engine lane B)
--
-- Authority: docs/superpowers/specs/2026-09-21-parameter-engine-design.md (the record) §8.1–§8.3;
-- recorded as DDL in metadata-db.md §4.26 / §4.27. Two tables, the templates/template_versions shape
-- (metadata-db §4.8/§4.9) minus the template-only columns:
--
-- 1. `parameter_sets` — one row per set, the INDEX over its versions. `id` is the UUID every surface
--    addresses a set by (record P24): generated by the application at create and KEPT by an import,
--    so it is stable across environments — no database default. `name` is the pipelines/templates
--    folder grammar (enforced in code, PipelineNameGrammar), unique per workspace FOREVER (versioning
--    §3.2, D59: a discarded set keeps its name). `display_name` / `description` index the CURRENT
--    RELEASED body (versioning §3.7's pipeline rule — they are content of the body and ride the
--    release). `current_version` is the sticky pointer (D60): NULL until the first release. No entity
--    status column: ACTIVE/DISCARDED is derived from the versions (versioning §3.2).
--
-- 2. `parameter_set_versions` — one row per version: the record's §3 document with `name` omitted
--    (`body_json`), its status (the same three and the same CHECK as template_versions), `body_hash`
--    = SHA-256 (hex) of the JSONB text projection of `body_json`, computed BY THE DATABASE in every
--    write (versioning §4.1's pipeline rule — one expression, so writer and reader cannot disagree),
--    the release/discard/via/created stamps with their CHECKs, and the one-draft partial unique index
--    that makes two simultaneous first writers race-safe (versioning §3.3). `ON DELETE CASCADE` from
--    the index row: a purged entity takes its versions (versioning §3.2 — only a draft-only entity is
--    ever purged). Nothing else references a version: no execution row, and the templates reverse
--    arrow (record §8.4) scans `body_json`, it holds no foreign key.
--
-- No trigger, no function, no extension: a pure additive migration touching no existing table.
--
-- DOWN PATH (manual; the lane's evidence runs it on a copy of the demo database). Refuse if any set
-- was ever written, then drop in dependency order:
--   DO $$ BEGIN IF EXISTS (SELECT 1 FROM parameter_sets)
--     THEN RAISE EXCEPTION 'parameter sets exist; V39 cannot be rolled back'; END IF; END $$;
--   DROP TABLE parameter_set_versions;
--   DROP TABLE parameter_sets;
--   DELETE FROM flyway_schema_history WHERE version = '39';
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. parameter_sets (metadata-db §4.26)
-- ---------------------------------------------------------------------------
CREATE TABLE parameter_sets (
    id              UUID        PRIMARY KEY,
    workspace_id    UUID        NOT NULL REFERENCES workspaces(id),
    name            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL,
    description     TEXT        NOT NULL DEFAULT '',
    current_version INTEGER     NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID        NOT NULL REFERENCES users(id),
    CONSTRAINT uq_parameter_sets_workspace_name UNIQUE (workspace_id, name),
    CONSTRAINT chk_parameter_sets_current_version CHECK (current_version IS NULL OR current_version >= 1)
);

-- ---------------------------------------------------------------------------
-- 2. parameter_set_versions (metadata-db §4.27)
-- ---------------------------------------------------------------------------
CREATE TABLE parameter_set_versions (
    parameter_set_id UUID        NOT NULL REFERENCES parameter_sets(id) ON DELETE CASCADE,
    version          INTEGER     NOT NULL,
    body_json        JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'DRAFT'
                         CONSTRAINT chk_parameter_set_versions_status CHECK (status IN ('DRAFT', 'RELEASED', 'DISCARDED')),
    body_hash        TEXT        NOT NULL,
    released_at      TIMESTAMPTZ NULL,
    released_by      UUID        REFERENCES users(id),
    discarded_at     TIMESTAMPTZ NULL,
    discarded_by     UUID        REFERENCES users(id),
    updated_by       UUID        REFERENCES users(id),
    updated_at       TIMESTAMPTZ NULL,
    created_via      TEXT        NOT NULL DEFAULT 'session',
    updated_via      TEXT        NOT NULL DEFAULT 'session',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       UUID        NOT NULL REFERENCES users(id),
    PRIMARY KEY (parameter_set_id, version),
    CONSTRAINT chk_parameter_set_versions_version CHECK (version >= 1),
    -- The body is an object whose versioned artifact never carries the set's name (record §8.1).
    CONSTRAINT chk_parameter_set_versions_body CHECK (jsonb_typeof(body_json) = 'object' AND NOT (body_json ? 'name')),
    -- A DRAFT has never been released; every other row has (released_at survives discard/restore).
    CONSTRAINT chk_parameter_set_versions_release_stamps CHECK (
        (status = 'DRAFT' AND released_at IS NULL AND released_by IS NULL)
        OR (status <> 'DRAFT' AND released_at IS NOT NULL)
    ),
    CONSTRAINT chk_parameter_set_versions_discard_stamps CHECK (
        (status = 'DISCARDED' AND discarded_at IS NOT NULL)
        OR (status <> 'DISCARDED' AND discarded_at IS NULL AND discarded_by IS NULL)
    ),
    CONSTRAINT chk_parameter_set_versions_via CHECK (
        created_via IN ('session', 'api_key', 'mcp') AND updated_via IN ('session', 'api_key', 'mcp')
    )
);

-- At most one DRAFT per set (versioning §3.3): the race loser's insert violates this and surfaces as
-- parameter.version.conflict carrying the winner's state.
CREATE UNIQUE INDEX uq_parameter_set_versions_one_draft
    ON parameter_set_versions (parameter_set_id) WHERE status = 'DRAFT';
