-- =============================================================================
-- V42 — visualizations and dashboards (#10, dashboards round one, lane L1a)
--
-- Authority: docs/superpowers/specs/2026-09-28-dashboard-implementation-spec.md §2.1 (the design record
-- is docs/superpowers/specs/2026-09-25-dashboard-authoring-design-draft.md, D30/D31/D34/D35/D56);
-- recorded as DDL in metadata-db.md §4.28–§4.33. Six tables:
--
-- 1–4. `visualizations` / `visualization_versions` and `dashboards` / `dashboard_versions` — the two
--    artifact families, each V39's `parameter_sets` / `parameter_set_versions` line for line with the
--    names changed. The index row's `id` is the UUID every surface addresses the artifact by (spec §4):
--    generated by the application at create and KEPT by an import (C29 refuses a taken id, never
--    re-issues), so no database default. `name` is the pipelines/templates folder grammar (enforced in
--    code, PipelineNameGrammar), unique per workspace FOREVER (versioning §3.2: a discarded artifact
--    keeps its name). `display_name` / `description` index the CURRENT RELEASED body; `current_version`
--    is the sticky pointer (D60), NULL until the first release. A version row holds the spec's §3.1 /
--    §3.2 document with `name` omitted (`body_json`), its status (DRAFT | RELEASED | DISCARDED),
--    `body_hash` = SHA-256 (hex) of the JSONB text projection, computed BY THE DATABASE in every write
--    (versioning §4.1's pipeline rule), the release/discard/via stamps with their CHECKs, and the
--    one-draft partial unique index that makes two simultaneous first writers race-safe (§3.3).
--
-- 5. `visualization_test_runs` — one agent test session over one visualization version (spec §11.2,
--    D56 (a)): the candidate's `body_hash` (a run whose hash no longer matches its version is void),
--    the session, the preview token's HASH and its expiry (the 32-byte capability itself is never
--    stored), the status, the per-case verdicts, the agent-reported environment and the server's
--    mechanical outcome (§11.3). DDL only in this lane — L4 writes and reads it. The run hangs off the
--    VERSION (a composite foreign key, ON DELETE CASCADE): purging a draft takes its evidence with it.
--
-- 6. `visualization_test_screenshots` — the one representative image of a run (D35), a separate table
--    so a run list never loads bytes: PNG or WebP, at most 4 MiB (spec §17), with the server's SHA-256
--    and the dimensions. DDL only here (L4).
--
-- No trigger, no function, no extension: a pure additive migration touching no existing table.
--
-- DOWN PATH (manual; the lane's evidence runs it on a copy of the demo database). Refuse if any
-- artifact or run was ever written, then drop in dependency order:
--   DO $$ BEGIN IF EXISTS (SELECT 1 FROM visualizations) OR EXISTS (SELECT 1 FROM dashboards)
--     THEN RAISE EXCEPTION 'visualizations or dashboards exist; V42 cannot be rolled back'; END IF; END $$;
--   DROP TABLE visualization_test_screenshots;
--   DROP TABLE visualization_test_runs;
--   DROP TABLE dashboard_versions;
--   DROP TABLE dashboards;
--   DROP TABLE visualization_versions;
--   DROP TABLE visualizations;
--   DELETE FROM flyway_schema_history WHERE version = '42';
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. visualizations (metadata-db §4.28)
-- ---------------------------------------------------------------------------
CREATE TABLE visualizations (
    id              UUID        PRIMARY KEY,
    workspace_id    UUID        NOT NULL REFERENCES workspaces(id),
    name            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL,
    description     TEXT        NOT NULL DEFAULT '',
    current_version INTEGER     NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID        NOT NULL REFERENCES users(id),
    CONSTRAINT uq_visualizations_workspace_name UNIQUE (workspace_id, name),
    CONSTRAINT chk_visualizations_current_version CHECK (current_version IS NULL OR current_version >= 1)
);

-- ---------------------------------------------------------------------------
-- 2. visualization_versions (metadata-db §4.29)
-- ---------------------------------------------------------------------------
CREATE TABLE visualization_versions (
    visualization_id UUID        NOT NULL REFERENCES visualizations(id) ON DELETE CASCADE,
    version          INTEGER     NOT NULL,
    body_json        JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'DRAFT'
                         CONSTRAINT chk_visualization_versions_status CHECK (status IN ('DRAFT', 'RELEASED', 'DISCARDED')),
    body_hash        TEXT        NOT NULL,
    released_at      TIMESTAMPTZ NULL,
    released_by      UUID        REFERENCES users(id),
    discarded_at     TIMESTAMPTZ NULL,
    discarded_by     UUID        REFERENCES users(id),
    updated_by       UUID        REFERENCES users(id),
    updated_at       TIMESTAMPTZ NULL,
    created_via      TEXT        NOT NULL DEFAULT 'session',
    updated_via      TEXT        NOT NULL DEFAULT 'session',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       UUID        NOT NULL REFERENCES users(id),
    PRIMARY KEY (visualization_id, version),
    CONSTRAINT chk_visualization_versions_version CHECK (version >= 1),
    -- The body is an object whose versioned artifact never carries the visualization's name (spec §3).
    CONSTRAINT chk_visualization_versions_body CHECK (jsonb_typeof(body_json) = 'object' AND NOT (body_json ? 'name')),
    -- A DRAFT has never been released; every other row has (released_at survives discard/restore).
    CONSTRAINT chk_visualization_versions_release_stamps CHECK (
        (status = 'DRAFT' AND released_at IS NULL AND released_by IS NULL)
        OR (status <> 'DRAFT' AND released_at IS NOT NULL)
    ),
    CONSTRAINT chk_visualization_versions_discard_stamps CHECK (
        (status = 'DISCARDED' AND discarded_at IS NOT NULL)
        OR (status <> 'DISCARDED' AND discarded_at IS NULL AND discarded_by IS NULL)
    ),
    CONSTRAINT chk_visualization_versions_via CHECK (
        created_via IN ('session', 'api_key', 'mcp') AND updated_via IN ('session', 'api_key', 'mcp')
    )
);

-- At most one DRAFT per visualization (versioning §3.3): the race loser's insert violates this and
-- surfaces as visualization.version.conflict carrying the winner's state.
CREATE UNIQUE INDEX uq_visualization_versions_one_draft
    ON visualization_versions (visualization_id) WHERE status = 'DRAFT';

-- ---------------------------------------------------------------------------
-- 3. dashboards (metadata-db §4.30)
-- ---------------------------------------------------------------------------
CREATE TABLE dashboards (
    id              UUID        PRIMARY KEY,
    workspace_id    UUID        NOT NULL REFERENCES workspaces(id),
    name            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL,
    description     TEXT        NOT NULL DEFAULT '',
    current_version INTEGER     NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID        NOT NULL REFERENCES users(id),
    CONSTRAINT uq_dashboards_workspace_name UNIQUE (workspace_id, name),
    CONSTRAINT chk_dashboards_current_version CHECK (current_version IS NULL OR current_version >= 1)
);

-- ---------------------------------------------------------------------------
-- 4. dashboard_versions (metadata-db §4.31)
-- ---------------------------------------------------------------------------
CREATE TABLE dashboard_versions (
    dashboard_id     UUID        NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE,
    version          INTEGER     NOT NULL,
    body_json        JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'DRAFT'
                         CONSTRAINT chk_dashboard_versions_status CHECK (status IN ('DRAFT', 'RELEASED', 'DISCARDED')),
    body_hash        TEXT        NOT NULL,
    released_at      TIMESTAMPTZ NULL,
    released_by      UUID        REFERENCES users(id),
    discarded_at     TIMESTAMPTZ NULL,
    discarded_by     UUID        REFERENCES users(id),
    updated_by       UUID        REFERENCES users(id),
    updated_at       TIMESTAMPTZ NULL,
    created_via      TEXT        NOT NULL DEFAULT 'session',
    updated_via      TEXT        NOT NULL DEFAULT 'session',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       UUID        NOT NULL REFERENCES users(id),
    PRIMARY KEY (dashboard_id, version),
    CONSTRAINT chk_dashboard_versions_version CHECK (version >= 1),
    -- The body is an object whose versioned artifact never carries the dashboard's name (spec §3).
    CONSTRAINT chk_dashboard_versions_body CHECK (jsonb_typeof(body_json) = 'object' AND NOT (body_json ? 'name')),
    CONSTRAINT chk_dashboard_versions_release_stamps CHECK (
        (status = 'DRAFT' AND released_at IS NULL AND released_by IS NULL)
        OR (status <> 'DRAFT' AND released_at IS NOT NULL)
    ),
    CONSTRAINT chk_dashboard_versions_discard_stamps CHECK (
        (status = 'DISCARDED' AND discarded_at IS NOT NULL)
        OR (status <> 'DISCARDED' AND discarded_at IS NULL AND discarded_by IS NULL)
    ),
    CONSTRAINT chk_dashboard_versions_via CHECK (
        created_via IN ('session', 'api_key', 'mcp') AND updated_via IN ('session', 'api_key', 'mcp')
    )
);

-- At most one DRAFT per dashboard (versioning §3.3).
CREATE UNIQUE INDEX uq_dashboard_versions_one_draft
    ON dashboard_versions (dashboard_id) WHERE status = 'DRAFT';

-- ---------------------------------------------------------------------------
-- 5. visualization_test_runs (metadata-db §4.32) — DDL only in L1a; L4 writes it
-- ---------------------------------------------------------------------------
CREATE TABLE visualization_test_runs (
    id                 UUID        PRIMARY KEY,
    visualization_id   UUID        NOT NULL,
    version            INTEGER     NOT NULL,
    body_hash          TEXT        NOT NULL,
    session_id         UUID        NOT NULL,
    preview_token_hash TEXT        NULL,
    expires_at         TIMESTAMPTZ NOT NULL,
    started_by         UUID        NOT NULL REFERENCES users(id),
    started_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at       TIMESTAMPTZ NULL,
    status             TEXT        NOT NULL DEFAULT 'RUNNING',
    cases_json         JSONB       NULL,
    environment_json   JSONB       NULL,
    mechanical_json    JSONB       NULL,
    -- The run belongs to one VERSION: purging a draft takes its evidence with it.
    CONSTRAINT fk_visualization_test_runs_version FOREIGN KEY (visualization_id, version)
        REFERENCES visualization_versions (visualization_id, version) ON DELETE CASCADE,
    CONSTRAINT uq_visualization_test_runs_session UNIQUE (visualization_id, version, session_id),
    CONSTRAINT chk_visualization_test_runs_status CHECK (status IN ('RUNNING', 'GREEN', 'RED', 'INCOMPLETE', 'EXPIRED')),
    -- A verdict is a completed run; a running one has none. EXPIRED is either (a session that timed
    -- out unsubmitted, or a completed run whose version's hash moved on).
    CONSTRAINT chk_visualization_test_runs_completed CHECK (
        (status = 'RUNNING' AND completed_at IS NULL)
        OR (status IN ('GREEN', 'RED', 'INCOMPLETE') AND completed_at IS NOT NULL)
        OR status = 'EXPIRED'
    ),
    CONSTRAINT chk_visualization_test_runs_json CHECK (
        (cases_json IS NULL OR jsonb_typeof(cases_json) = 'array')
        AND (environment_json IS NULL OR jsonb_typeof(environment_json) = 'object')
        AND (mechanical_json IS NULL OR jsonb_typeof(mechanical_json) = 'object')
    )
);

-- ---------------------------------------------------------------------------
-- 6. visualization_test_screenshots (metadata-db §4.33) — DDL only in L1a; L4 writes it
-- ---------------------------------------------------------------------------
CREATE TABLE visualization_test_screenshots (
    run_id        UUID        PRIMARY KEY REFERENCES visualization_test_runs(id) ON DELETE CASCADE,
    media_type    TEXT        NOT NULL,
    bytes         BYTEA       NOT NULL,
    sha256        TEXT        NOT NULL,
    width         INTEGER     NOT NULL,
    height        INTEGER     NOT NULL,
    depicted_case TEXT        NULL,
    uploaded_by   UUID        NOT NULL REFERENCES users(id),
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_visualization_test_screenshots_media_type CHECK (media_type IN ('image/png', 'image/webp')),
    -- The spec §17 cap: 4 MiB, independent of the platform's 2 MiB request-body cap.
    CONSTRAINT chk_visualization_test_screenshots_size CHECK (octet_length(bytes) BETWEEN 1 AND 4194304),
    CONSTRAINT chk_visualization_test_screenshots_sha256 CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_visualization_test_screenshots_dimensions CHECK (width >= 1 AND height >= 1)
);
