#!/usr/bin/env bash
# scripts/lib/docker-stub.sh — the RECORD-AND-REFUSE docker stub the app.sh tests run
# against. SOURCED, not executed (same pattern as lib/gate-stages.sh, lib/scan-tools.sh).
#
# P34, and it is the third stack-down incident from a lane touching docker: the 075
# secrets test shipped a stub that forwarded anything it did not recognise to the real
# binary "because `compose config` needs a daemon". `app.sh --start` then issued a real
# `compose up -d --wait`, under the DEFAULT project, and stopped the owner's live stack
# for twelve minutes. A stub that forwards a verb it did not mean to forward IS the real
# binary; `-p` is not what decides which project a compose command touches.
#
# So the contract here is inverted from that one:
#
#   * every invocation is RECORDED, argv-per-line, to $DOCKER_STUB_LOG;
#   * a FAKE is a shell case the caller wrote by hand — it answers and returns;
#   * anything else EXITS NON-ZERO and says so on stderr, loudly, naming the argv.
#     Never a silent `exit 0`, which is how an unexpected call hides, and never a
#     fallthrough to $(command -v docker).
#
# The one exception any caller may grant is an explicit ALLOWLIST of read-only verbs
# (`compose config` renders a model and starts nothing), passed by name — never a
# pattern, never a default.
#
#   source scripts/lib/docker-stub.sh
#   write_docker_stub "$tmp/bin/docker" "$tmp/docker-argv.log" <<'FAKE'
#   if [[ $* == *"up -d --wait"* ]]; then exit 1; fi
#   FAKE
#
# The fake body is bash, evaluated after the recording and before the refusal, with the
# original arguments in "$@". `stub_refused_lines <log>` reads back what was refused, so
# a test can PROVE the refusal fired rather than assert it by reading the source.

# write_docker_stub <path> <argv-log> [real-docker-passthrough-verb ...]
# The fake body is read from stdin.
write_docker_stub() {
  local path="$1" log="$2"
  shift 2
  # `${@:+"$@"}` and not `("$@")`: under the callers' `set -u` an empty array expansion
  # is an unbound-variable error on bash 3.2 (macOS's /bin/bash), and every caller so far
  # passes no allowlist at all.
  local allow=(${@:+"$@"})
  local body
  body=$(cat)
  mkdir -p "$(dirname "$path")"
  {
    echo '#!/usr/bin/env bash'
    echo '# GENERATED by scripts/lib/docker-stub.sh — records every call, refuses the rest.'
    echo "printf '%s\\n' \"\$*\" >>\"$log\""
    printf '%s\n' "$body"
    # `${allow[@]+…}`: bash 3.2 (macOS's /bin/bash) treats an EMPTY array's `"${a[@]}"` as
    # an unbound variable under `set -u`, and no caller passes an allowlist today.
    for verb in ${allow[@]+"${allow[@]}"}; do
      # An allowlisted verb reaches the real daemon. It must be read-only, and the caller
      # is the one asserting that — hence one line per verb, spelled out, in the test.
      cat <<ALLOW
if [[ \${1:-} == compose ]]; then
  for arg in "\$@"; do
    if [[ \$arg == $verb ]]; then exec "\$DOCKER_STUB_REAL" "\$@"; fi
  done
fi
ALLOW
    done
    cat <<'REFUSE'
printf 'docker-stub: REFUSED an invocation the test did not fake: docker %s\n' "$*" >&2
printf 'docker-stub: (P34 — a stub that forwards what it does not recognise IS the real\n' >&2
printf 'docker-stub:  binary, and the real binary reaches this machine live stacks.)\n' >&2
exit 97
REFUSE
  } >"$path"
  chmod +x "$path"
  DOCKER_STUB_REAL="$(command -v docker || true)"
  export DOCKER_STUB_REAL
  : >"$log"
}

# stub_refused_lines <argv-log> <bin-dir> — replay the log through the stub itself and
# print every argv it refuses. Used to SHOW the refusal in the gate rather than claim it.
stub_refused_lines() {
  local log="$1" bin="$2" line
  while IFS= read -r line; do
    # shellcheck disable=SC2086 # the log stores argv space-joined, which is what we replay
    if ! "$bin/docker" $line >/dev/null 2>&1; then
      printf 'REFUSED: docker %s\n' "$line"
    fi
  done <"$log"
}
