package co.datapipelines.web.ui

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test
import org.springframework.core.io.support.PathMatchingResourcePatternResolver

/**
 * The site-chrome bundle's parity guard (111 §C).
 *
 * `static/site/css/site-chrome.css` is a GENERATED byte-exact concatenation of the three
 * design-system foundation sheets (tokens, base, motion — in that order, under an authored
 * header). It exists because the public head loaded the three as separate render-blocking
 * requests and failed `scripts/site-lighthouse.sh`'s performance floor on the request chain
 * alone; one request, same bytes, same cascade order.
 *
 * A generated copy is a drift hazard by construction: the design system updates and the
 * bundle silently serves last month's tokens. This test is the mechanism that makes the
 * drift loud — byte-equality against the three sources, so the build fails until
 * `scripts/build-site-chrome.sh` regenerates it. The homepage and the site layout are the
 * two consumers; the app's own layouts keep their individual links and are unaffected.
 */
class SiteCssBundleParityTest {
    private val resolver = PathMatchingResourcePatternResolver(javaClass.classLoader)

    private fun read(path: String): String =
        resolver.getResource("classpath:static/$path").inputStream.readBytes().decodeToString()

    @Test
    fun `the bundle is exactly the header plus the three foundation sheets, in order`() {
        val bundle = read("site/css/site-chrome.css")

        // Non-vacuity: a truncated bundle must fail on shape before it can pass on content.
        check(bundle.startsWith(HEADER_PREFIX)) { "site-chrome.css lost its derivation header" }

        val tokens = read("vendor/design-system/tokens.css")
        val base = read("vendor/design-system/base.css")
        val motion = read("vendor/design-system/motion.css")
        val auto = read("vendor/design-system/themes/auto.css")
        val siteCss = read("site/css/site.css")

        val expectedBody = tokens + "\n" + base + "\n" + motion + "\n" + auto + "\n" + siteCss
        val body = bundle.substringAfter(HEADER_PREFIX)
        (body.trimEnd() shouldBe expectedBody.trimEnd())
    }

    @Test
    fun `the public head loads the bundle, not the three separate sheets`() {
        // The performance fix is load-bearing: if a template reintroduces the per-sheet links
        // the render-blocking chain (and the Lighthouse failure) comes back with it.
        val templates =
            listOf("templates/site/_layout.html", "templates/site/index.html")
                .associateWith { resolver.getResource(it).inputStream.readBytes().decodeToString() }
        templates.forEach { (name, source) ->
            source.contains("site/css/site-chrome.css") shouldBe true
            source.contains("vendor/design-system/tokens.css") shouldBe false
            source.contains("vendor/design-system/base.css") shouldBe false
            source.contains("vendor/design-system/motion.css") shouldBe false
            // The theme swap sheet stays a separate link AFTER the bundle, but DISABLED:
            // auto's values ride the bundle, site.js enables the link only for light/dark,
            // so the swap sheet never costs a render-blocking request.
            source.contains("""themes/auto.css" disabled""") shouldBe true
            // The mono faces ride the late sheet, off the critical chain.
            source.contains("site-fonts-mono.css") shouldBe true
            source.contains("data-late-style") shouldBe true
        }
    }

    private companion object {
        const val HEADER_PREFIX = "   ============================================================ */"
    }
}
